name=input("Enter name")
idno=input("Enter idno")
collegename=input("enter collegename")
mailid=input("Enter mailid")
mobileno=int(input("Enter mobileno"))
percentage=float(input("Enter percentage"))
print(f"name:{name}")
print(f"Id no:{idno}")
print(f"college name:{collegename}")
print(f"mail id:{mailid}")
print(f"mobile no:{mobileno}")
print("percentage: {:.if}%".format(percentage))
